model:
  si:
    class_path: omg.si.stochastic_interpolants.StochasticInterpolants
    init_args:
      stochastic_interpolants:
        # chemical species
        - class_path: omg.si.discrete_flow_matching_mask.DiscreteFlowMatchingMask
          init_args:
            noise: 0.18946955217679085
        # fractional coordinates
        - class_path: omg.si.single_stochastic_interpolant.SingleStochasticInterpolant
          init_args:
            interpolant: omg.si.interpolants.PeriodicLinearInterpolant
            gamma: 
              class_path: omg.si.gamma.LatentGammaSqrt
              init_args:
                a: 0.018159684059653552
            epsilon: 
              class_path: omg.si.epsilon.VanishingEpsilon
              init_args:
                c: 9.74900863316411
                mu: 0.17191546490562354
                sigma: 0.029425925880471573
            differential_equation_type: "SDE"
            integrator_kwargs:
              method: "euler"
              dt: 0.0014076164225116372
            velocity_annealing_factor: 6.334345265874859
            correct_center_of_mass_motion: true
        # lattice vectors
        - class_path: omg.si.single_stochastic_interpolant.SingleStochasticInterpolant
          init_args:
            interpolant: omg.si.interpolants.LinearInterpolant
            gamma: 
              class_path: omg.si.gamma.LatentGammaSqrt
              init_args:
                a: 0.8480953426626178
            epsilon: 
              class_path: omg.si.epsilon.VanishingEpsilon
              init_args:
                c: 3.673041703474942
                mu: 0.0706838941982046
                sigma: 0.01812545867373373
            differential_equation_type: "SDE"
            integrator_kwargs:
              method: "euler"
              dt: 0.001469808747060597
            velocity_annealing_factor: 0.2916081322471492
            correct_center_of_mass_motion: false
      data_fields:
        # if the order of the data_fields changes,
        # the order of the above StochasticInterpolant inputs must also change
        - "species"
        - "pos"
        - "cell"
      integration_time_steps: 710
  relative_si_costs:
    species_loss: 0.35838215846575894
    pos_loss_b: 0.5183735506925028
    pos_loss_z: 0.0007900924652522647
    cell_loss_b: 0.0044136759736567365
    cell_loss_z: 0.11804052240282935
  sampler:
    class_path: omg.sampler.sample_from_rng.SampleFromRNG
    init_args:
      pos_distribution: null
      cell_distribution: 
        class_path: omg.sampler.distributions.InformedLatticeDistribution
        init_args:
          dataset_name: mp_20
      species_distribution:
        class_path: omg.sampler.distributions.MaskDistribution
  model:
    class_path: omg.model.model.Model
    init_args:
      encoder:
        class_path: omg.model.encoders.cspnet_full.CSPNetFull
      head:
        class_path: omg.model.heads.pass_through.PassThrough
      time_embedder:
        class_path: omg.model.model_utils.SinusoidalTimeEmbeddings
        init_args:
          dim: 256
  use_min_perm_dist: True
  float_32_matmul_precision: "high"
  validation_mode: "dng_eval"
  dataset_name: "mp_20"
data:
  train_dataset:
    class_path: omg.datamodule.dataloader.OMGTorchDataset
    init_args:
      dataset:
        class_path: omg.datamodule.datamodule.DataModule
        init_args:
          lmdb_paths:
           - "data/mp_20/train.lmdb"
      niggli: False
  val_dataset:
    class_path: omg.datamodule.dataloader.OMGTorchDataset
    init_args:
      dataset:
        class_path: omg.datamodule.datamodule.DataModule
        init_args:
          lmdb_paths:
           - "data/mp_20/val.lmdb"
      niggli: False
  predict_dataset:
    class_path: omg.datamodule.dataloader.OMGTorchDataset
    init_args:
      dataset:
        class_path: omg.datamodule.datamodule.DataModule
        init_args:
          lmdb_paths:
           - "data/mp_20/test.lmdb"
      niggli: False
  batch_size: 32
  #num_workers: 4
  #pin_memory: True
  #persistent_workers: True
trainer:
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        filename: "best_val_loss_total"
        save_top_k: 1
        monitor: "val_loss_total"
        save_weights_only: true
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        filename: "best_val_dng_eval"
        save_top_k: 1
        monitor: "dng_eval"
        save_weights_only: true
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        filename: "best_val_wdist_density"
        save_top_k: 1
        monitor: "wdist_density"
        save_weights_only: true
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        filename: "best_val_wdist_Nary"
        save_top_k: 1
        monitor: "wdist_narity"
        save_weights_only: true
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        filename: "best_val_wdist_CN"
        save_top_k: 1
        monitor: "wdist_coordination_numbers"
        save_weights_only: true
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        filename: "best_val_cov_precision"
        save_top_k: 1
        monitor: "cov_precision"
        mode: "max"
        save_weights_only: true
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        filename: "best_val_cov_recall"
        save_top_k: 1
        monitor: "cov_recall"
        mode: "max"
        save_weights_only: true
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        filename: "best_val_validity"
        save_top_k: 1
        monitor: "valid_rate"
        mode: "max"
        save_weights_only: true
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        save_top_k: -1  # Store every checkpoint after 100 epochs.
        monitor: "val_loss_total"
        every_n_epochs: 100
        save_weights_only: false
  gradient_clip_val: 0.5
  gradient_clip_algorithm: "value"
  num_sanity_val_steps: 0
  precision: "32-true"
  max_epochs: 2000
  enable_progress_bar: true
  check_val_every_n_epoch: 100
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.00019745455354877462
    weight_decay: 0.0003111161289640361
lr_scheduler:
  class_path: torch.optim.lr_scheduler.CosineAnnealingLR
  init_args:
    T_max: 2000
    eta_min: 1e-07